[tool.poetry]
name = "poetry-devcontainer"
version = "0.1.0"
description = ""
authors = ["UserName <sample@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
